---
title: "Relative abundance analysis of Fishing Landings dataset"
author: "Author: Emma Strand; emma_strand@uri.edu"
output:
  github_document: default
  pdf_document:
    keep_tex: yes
  html_document:
    toc: yes
    toc_depth: 6
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Contents 

- [**Reading in datafiles**](#data)  

## <a name="data"></a> **Reading in datafiles**

```{r, message=FALSE, warning=FALSE}
library(plyr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(readxl)
library(lubridate)
library(Hmisc)
library(writexl)
library(naniar)
library(Rmisc)
library(phyloseq)
library(stats)
library(lme4)
library(car)
library(vegan)
library(funrar) #make relative fxn 
```

## Read in the data frame that is the output of the QC script and create matrix for phyloseq input. 

```{r}
# read in excel file
div_df <- read_excel("data/cleaned-Fishlandings-data-FEB 2023 JMCC.xlsx") %>% #read in excel file 
  unite(survey_id, Operation_date, fisher_id, sep = "-", remove = FALSE) # creating a new variable called survey id

data_matrix <- div_df %>% # modified original 
  dplyr::select(survey_id, trap_type, scientific_name, number_of_fish) %>% # selecting only desired columns for matrix
  mutate(trap_type = case_when(
    trap_type == "MODIFIED TRAP" ~ "Experimental",
    trap_type == "UNMODIFIED" ~ "Control")) %>% # renaming modified and unmodified to experimental and control
  subset(trap_type == "Experimental" | trap_type == "Control") %>%
  mutate(number_of_fish = if_else(is.na(number_of_fish), 1, number_of_fish)) %>%
  spread(., scientific_name, number_of_fish) %>% # creating matrix from fish name and number columns
  column_to_rownames(var="survey_id") # moving survey id column to row names 

data_matrix[is.na(data_matrix)] <- 0 #changing NAs to zeros 

#meta <- df %>% select(survey_id, trap_type, landing_site) %>% distinct()
```
# Relative abundance 

## Making relative abundance dataframe 

```{r}
otu <- data.matrix(data_matrix) # turning into data matrix 
rel <- make_relative(otu) # making relative abundance 
rel <- as.data.frame(rel) # turning this back into a dataframe 
```

## Combining back with metadata 

```{r}
rel_meta <- tibble::rownames_to_column(rel, "trap_type")
#rel_meta <- merge(meta, rel_meta, by = "trap_type")
rel_meta <- rel_meta %>% #filter(!is.na(trap_type)) %>%
  gather(key=scientific_name, value = relabund, 2:122) %>%
  #subset(trap_type == "MODIFIED" | trap_type == "UNMODIFIED") %>%
  filter(!is.na(relabund)) %>%
  filter(relabund > 0.1)
```

## Plotting 

```{r}
rel_meta %>%
  ggplot(., aes(x = trap_type, y = reorder(scientific_name, relabund))) + 
  geom_tile(aes(fill = relabund), color = "grey") +
  ggtitle("Relative abundance") +
  scale_fill_distiller(palette = "Blues", direction=100, labels = scales::label_percent(scale=100)) + 
  theme_classic() +
  theme(#axis.text.x.bottom = element_text(angle = 60, hjust=1),
        axis.text.y = element_text(colour = 'black', size = 9, face = 'italic')) + 
  #facet_grid(~trap_type, scales = "free",) +
  labs(x="Trap Type", fill="Relative Abundance", y="Scientific name") 
```

## PCA on relative abundance 

```{r}
# pca_rel <- scale(rel)
# meta
# 
# adonis2(pca_rel ~ trap_type*landing_site, data = meta, method='eu')
# 
# pca.results <- prcomp(pca_rel, retx=TRUE) # principal components analysis on sym data
# summary(pca.relabundance.results)
```

